apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-server
spec:
  selector:
    app.kubernetes.io/name: postgresql
  type: LoadBalancer
  ports:
    - name: postgres-port
      protocol: TCP
      port: 5432
      targetPort: 5432