apiVersion: v1
kind: Namespace
metadata:
  name: postgres-storage

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-storage-service-account
  namespace: postgres-storage

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgres-storage-provisioner-role
  namespace: postgres-storage
rules:
  - apiGroups: [""]
    resources: ["nodes", "persistentvolumeclaims", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["endpoints", "persistentvolumes", "pods"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: postgres-storage-provisioner-bind
  namespace: postgres-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: postgres-storage-provisioner-role
subjects:
  - kind: ServiceAccount
    name: postgres-storage-service-account
    namespace: postgres-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-storage-provisioner
  namespace: postgres-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-storage-provisioner
  template:
    metadata:
      labels:
        app: postgres-storage-provisioner
    spec:
      serviceAccountName: postgres-storage-service-account
      containers:
        - name: postgres-storage-provisioner
          image: rancher/postgres-storage-provisioner:master-head
          imagePullPolicy: IfNotPresent
          command:
            - postgres-storage-provisioner
            - --debug
            - start
            - --config
            - /etc/config/config.json
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: config-volume
          configMap:
            name: postgres-storage-config

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-storage-config
  namespace: postgres-storage
data:
  config.json: |-
    {
            "nodePathMap":[
            {
                    "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                    "paths":["/opt/postgres-storage-provisioner"]
            }
            ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent
