---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-storage-provisioner-workaround
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-storage-provisioner-workaround
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-storage-provisioner-workaround
subjects:
  - kind: ServiceAccount
    name: postgres-storage-provisioner-service-account
