- name: Install git on Controller
  hosts: controller
  become: yes
  gather_facts: no
  tasks:
    - name: Installing git-all
      ansible.builtin.apt:
        pkg:
          - git-all

- name: Install k3s on Controller
  hosts: controller
  gather_facts: yes
  tasks:
    - name: Run k3s script      
      shell: curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --bind-address 192.168.1.145 --disable traefik
      register: k3s_script_controller
    - debug: var=k3s_script_controller.stdout_lines
    
    - name: Get app token
      become: yes
      shell: cat /var/lib/rancher/k3s/server/token
      register: cluster_token
    - debug: var=cluster_token.stdout
    
    - name: Create ~/.kube directory
      become: yes
      become_user: ftathiago
      file:
        path: ~/.kube
        state: directory
        
    - name: Copy .kube/config
      become: yes
      become_user: ftathiago
      ansible.builtin.shell:
         sudo cat /etc/rancher/k3s/k3s.yaml >  ~/.kube/config

    - name: Remove Traefik manifest
      become: yes
      file: 
        path: /var/lib/rancher/k3s/server/manifests/traefik.yaml
        state: absent
