- name: Prepare Disk
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    # - name: Discover disks
    #   shell: "lsblk -f"
    #   register: disk_list
    # - debug: var=disk_list.stdout_lines
    # - name: Fast format disk
    #   shell: "mkfs.ext4 /dev/{{ var_disk }}"      
    # - name: Create disk dir
    #   ansible.builtin.file:
    #     path: /mnt/ssd
    #     state: directory
    # - name: Revel uuid disks
    #   shell: "blkid -s UUID -o value /dev/{{ var_disk }}"
    #   register: uuid_disk
    # - debug: var=uuid_disk.stdout_lines
    # - name: Mount disks
    #   ansible.posix.mount:
    #     path: /mnt/ssd
    #     src: UUID={{ var_disk_uuid }} 
    #     fstype: ext4 
    #     state: mounted
    #   register: mount_disk
    # - debug: var=mount_disk
    # - name: UnMount disks
    #   ansible.posix.mount:
    #     path: /storage01
    #     state: unmounted
    #   register: unmount_disk
    # - debug: var=unmount_disk