controller:
  hosts:  
    controller_node:
      ansible_host: 192.168.1.145 
      ansible_user: ftathiago
      ansible_password: ***REMOVED***
workers:
  vars:
    cluster_token: K1055df49fbc7c23132f505999efed12f46580bb51e3660948fa68220e4f6e81c9a::server:53ddc7da6908d464644e197094c1a548
  hosts:           
    worker1:
      ansible_host: 192.168.1.146
      ansible_user: ftathiago
      ansible_password: ***REMOVED***
    worker2:
      ansible_host: 192.168.1.147
      ansible_user: ftathiago
      ansible_password: ***REMOVED***
