controller:
  hosts:  
    controller_node:
      ansible_host: 192.168.1.145 
      ansible_user: ftathiago
      ansible_password: ***REMOVED***
workers:
  vars:
    cluster_token: K100ae08a2cfe9c5ef45887c07b948572e2544f93f9b8909d4594025b2f120c2236::server:e33512e1db3e3ae869fac3c197b6fa2e
  hosts:           
    worker1:
      ansible_host: 192.168.1.146
      ansible_user: ftathiago
      ansible_password: ***REMOVED***
    worker2:
      ansible_host: 192.168.1.147
      ansible_user: ftathiago
      ansible_password: ***REMOVED***
