apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-client
  namespace: kafka-broker
spec:
  selector:
    matchLabels:
      app: kafka-client
  template:
    metadata:
      labels:
        app: kafka-client
    spec:
      containers:
      - name: kafka-client
        image: bitnami/kafka:latest
        command:
          - bash
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
